# Generated by Django 5.2.10 on 2026-02-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único identificador', max_length=50, unique=True, verbose_name='Código de Artículo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Artículo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del artículo', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa y Accesorios'), ('hogar', 'Hogar y Muebles'), ('alimentos', 'Alimentos'), ('bebidas', 'Bebidas'), ('limpieza', 'Limpieza'), ('papeleria', 'Papelería'), ('herramientas', 'Herramientas'), ('deportes', 'Deportes'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Categoría')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio de Venta')),
                ('cantidad_stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('cantidad_minima', models.IntegerField(default=5, help_text='Cantidad mínima antes de alerta', verbose_name='Stock Mínimo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado')], default='activo', max_length=20, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Estante A-5, Pasillo 3', max_length=100, verbose_name='Ubicación en Almacén')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Fecha Última Compra')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre', 'categoria'],
                'indexes': [models.Index(fields=['codigo'], name='articulo_ar_codigo_a7bb3e_idx'), models.Index(fields=['nombre'], name='articulo_ar_nombre_139dfd_idx'), models.Index(fields=['categoria'], name='articulo_ar_categor_104006_idx'), models.Index(fields=['estado'], name='articulo_ar_estado_3191dc_idx')],
            },
        ),
    ]
